server {
    listen 443 ssl;
    server_name 192.168.129.200;

    ssl_certificate     /etc/nginx/certs/nextcloud.crt;
    ssl_certificate_key /etc/nginx/certs/nextcloud.key;

    client_max_body_size 512M;

    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
